### PR TITLE
Upgrade deps

### LINKED ISSUE #13: Upgrade all dependencies
image

we should definitely address this

_Originally posted by @marc0olo in https://github.com/aeternity/aepp-boilerplate-vue/issues/11#issuecomment-1194585711_

And possibly turn on dependabot

### PR DESCRIPTION
**Pull request by janmichek**
fixes #13 

All works without errors

obrazek

I cannot turn on Dependabot as I don't have enough permissions. I believe the owner is @thepiwo 

It is branched from master, so it can be directly reviewed and merged.

### CODE REVIEW

**Comment by marc0olo** [comment]
> I cannot turn on Dependabot as I don't have enough permissions. I believe the owner is @thepiwo

let me make you maintainer of this repo ;-)

**Comment by marc0olo** [comment]
@janmichek let's please add to the readme the node requirements. I am getting a lot of errors right now

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'espree@9.3.2',
npm WARN EBADENGINE   required: { node: '^12.22.0 || ^14.17.0 || >=16.0.0' },
npm WARN EBADENGINE   current: { node: 'v14.16.1', npm: '7.12.1' }
npm WARN EBADENGINE }
```

**Comment by janmichek** [comment]
> @janmichek let's please add to the readme the node requirements. I am getting a lot of errors right now
> 
> ```
> npm WARN EBADENGINE Unsupported engine {
> npm WARN EBADENGINE   package: 'espree@9.3.2',
> npm WARN EBADENGINE   required: { node: '^12.22.0 || ^14.17.0 || >=16.0.0' },
> npm WARN EBADENGINE   current: { node: 'v14.16.1', npm: '7.12.1' }
> npm WARN EBADENGINE }
> ```

added

**Comment by janmichek** [comment]
> > I cannot turn on Dependabot as I don't have enough permissions. I believe the owner is @thepiwo
> 
> let me make you maintainer of this repo ;-)

Dependabot turned on

**Comment by marc0olo** [comment]
@janmichek I have a problem executing  `npm install` with node `v16.16.0`

# `v16.16.0`
```sh
Now using node v16.16.0 (npm v8.11.0)
marc0olo@DESKTOP-B1QLEDL:~/git/aeternity/aepp-boilerplate-vue$ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @vue/cli-plugin-unit-jest@5.0.8
npm ERR! Found: ts-jest@24.3.0
npm ERR! node_modules/ts-jest
npm ERR!   peerOptional ts-jest@">= 24 < 27 " from vue-jest@5.0.0-alpha.10
npm ERR!   node_modules/vue-jest
npm ERR!     dev vue-jest@"^5.0.0-0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional ts-jest@"^27.0.4" from @vue/cli-plugin-unit-jest@5.0.8
npm ERR! node_modules/@vue/cli-plugin-unit-jest
npm ERR!   dev @vue/cli-plugin-unit-jest@"~5.0.8" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: ts-jest@27.1.5
npm ERR! node_modules/ts-jest
npm ERR!   peerOptional ts-jest@"^27.0.4" from @vue/cli-plugin-unit-jest@5.0.8
npm ERR!   node_modules/@vue/cli-plugin-unit-jest
npm ERR!     dev @vue/cli-plugin-unit-jest@"~5.0.8" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/marc0olo/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/marc0olo/.npm/_logs/2022-07-27T08_48_27_723Z-debug-0.log
```

same problem for newer versions like 17 and 18.

any idea?!

**Comment by janmichek** [comment]
> @janmichek I have a problem executing `npm install` with node `v16.16.0`
> # `v16.16.0`
> 
> ```shell
> Now using node v16.16.0 (npm v8.11.0)
> marc0olo@DESKTOP-B1QLEDL:~/git/aeternity/aepp-boilerplate-vue$ npm install
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE could not resolve
> npm ERR! 
> npm ERR! While resolving: @vue/cli-plugin-unit-jest@5.0.8
> npm ERR! Found: ts-jest@24.3.0
> npm ERR! node_modules/ts-jest
> npm ERR!   peerOptional ts-jest@">= 24 < 27 " from vue-jest@5.0.0-alpha.10
> npm ERR!   node_modules/vue-jest
> npm ERR!     dev vue-jest@"^5.0.0-0" from the root project
> npm ERR! 
> npm ERR! Could not resolve dependency:
> npm ERR! peerOptional ts-jest@"^27.0.4" from @vue/cli-plugin-unit-jest@5.0.8
> npm ERR! node_modules/@vue/cli-plugin-unit-jest
> npm ERR!   dev @vue/cli-plugin-unit-jest@"~5.0.8" from the root project
> npm ERR! 
> npm ERR! Conflicting peer dependency: ts-jest@27.1.5
> npm ERR! node_modules/ts-jest
> npm ERR!   peerOptional ts-jest@"^27.0.4" from @vue/cli-plugin-unit-jest@5.0.8
> npm ERR!   node_modules/@vue/cli-plugin-unit-jest
> npm ERR!     dev @vue/cli-plugin-unit-jest@"~5.0.8" from the root project
> npm ERR! 
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force, or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR! 
> npm ERR! See /home/marc0olo/.npm/eresolve-report.txt for a full report.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/marc0olo/.npm/_logs/2022-07-27T08_48_27_723Z-debug-0.log
> ```
> 
> same problem for newer versions like 17 and 18.
> 
> any idea?!

I have the same Node version and have the same issue.
To be honest I didn't elaborate on them an installed it with `--force`.

I have another more general question - maybe we can consult on another place.
Why don't we use `yarn` ? :D
Its first time I am using `npm` in team. As far as I know yarn has much more advantages - faster and safer.
Also installing with yarn produces no problem.

**Comment by marc0olo** [comment]
then let's remove the package lock and encourage to use yarn. maybe that's a separate topic to rise. I also don't like that we sometimes use yarn and sometimes use npm.

but certainly we cannot advertise the current state where everybody will run into this problem when executing `npm install` 😅

**Comment by marc0olo** [comment]
the goal with this repo in general is to have the smoothest way to onboard Vue devs to aeternity. if they fail to execute `npm install` this does not reflect well on us.

**Comment by janmichek** [comment]
> the goal with this repo in general is to have the smoothest way to onboard Vue devs to aeternity. if they fail to execute `npm install` this does not reflect well on us.

Agree on this. I have converted it to yarn installation and noted to readme.
I think using yarn is nothing exotic nowadays.
I will try to rise this general question. Let's see how popular it will be 😅

**Review by marc0olo — APPROVED** [review]

**Pull request merged**
