### PR TITLE
Update boilerplate

### LINKED ISSUE #1: Update the Boilerplate
The boilerplate needs some love:

- [x] Update the SDK to the latest release (currently `v8.2.1`)
- [x] Make sure that the boilerplate still connects & works with
    - [x] Superhero Wallet
- [x] Update all other dependencies to the newest version
- [x] Switch CI to Github Actions

### PR DESCRIPTION
**Pull request by the-icarus**
Changes:
- Switch from `travis ci` to `GitHub Actions`
- Update dependencies to latest versions
- Remove deprecated dependencies `raw-loader` and `file-loader`
- Add required polyfills which were included by default in webpack v4: `process`, `stream-browserify`, `path-browserify`, `crypto-browserify`
- Add `Buffer` dependency to webpack config
- Use prebuild `aepp-components` from npm because of build issues
- Remove `BaseAepp` from docs and `aeternity.js`

Closes #1

### CODE REVIEW

**Comment by the-icarus** [comment]
@marc0olo PR is finalized and ready for review

**Review by marc0olo — COMMENTED** [review]
Thanks @the-icarus!

I think in the `src/utils/aeternity.js` we can polish the boilerplate still a bit. I think there is some deadcode related to the reverse iFrame approach and some outcommented stuff. we can also improve the import handling of SDK modules.

besides that it would be great to have an updated README that reflects the new state of the application :-)

for me it's fine to not have the aepp-components library included anymore.

also looking forward to the comments of @kenodressel regarding the boilerplate

**Comment by kenodressel** [comment]
Hm can you describe how `aepp-components` is incompatible?

**Comment by the-icarus** [comment]
@kenodressel The main issue is that some assets seem to be build twice. Once webpack executes the build the overwrite gets reported as error and webpack terminates.
I'm not sure what's the exact reason but I guess the main issue is related to how we consume the `aepp-components`. Once we install the package everything gets build because we consume the raw git branch and not a precompiled package.

**Comment by the-icarus** [comment]
@marc0olo The requested changes are applied. Please review again.

**Comment by marc0olo** [comment]
@the-icarus I think we should also update the aepp-components related stuff in the README as long as we decide to drop it.

@kenodressel what's your take on that? I am not sure if it works without problems using the latest published release instead of a specific github branch of aepp-components. we could also think about inlcuding updating the dependencies of aepp-components simultaneously in this bounty. but then we should probably increase the reward 🤔

**Comment by the-icarus** [comment]
@marc0olo Latest updates on this.
- Updated packages to latest versions
- Added prebuild `@aeternity/aepp-components` package from npm which works fine
- Updated the docs to include `aepp-components` again

I would like to request final review for this PR

**Comment by marc0olo** [comment]
wondering about which wallet is being used in the detection now. I have Superhero Wallet active and connected to mainnet but get following information when starting the application with the latest state:

image

maybe I missed sth. when pulling the updated version 🤔

**Comment by the-icarus** [comment]
@marc0olo I will double check today and get back to you.

**Comment by marc0olo** [comment]
ok I checked again with a fresh checkout. for me it's fine now. every requirement is fulfilled :-)

image

@kenodressel can you also have a quick look and confirm?

**Review by kenodressel — APPROVED** [review]
LGTM

**Pull request merged**
