### PR TITLE
Update sdk to 13

### PR DESCRIPTION
**Pull request by davidyuk**

### CODE REVIEW

**Comment by thepiwo** [comment]
would it be also good to migrate to vite and eventually pinia?

**Review by marc0olo — COMMENTED** [review]
I see following log in the console:

```js
caught (in promise) NoWalletConnectedError: You are not connected to Wallet
    at Proxy._ensureConnected (AeSdkAepp.ts:172:1)
    at Proxy._ensureAccountAccess (AeSdkAepp.ts:176:1)
    at Proxy._resolveAccount (AeSdkAepp.ts:73:1)
    at get address (AeSdkBase.ts:131:1)
    at Reflect.get (<anonymous>)
    at Object.get (reactivity.esm-bundler.js:492:1)
    at fetchAccountInfo (wallet.js:87:1)
    at connectToNode (wallet.js:101:1)
    at Proxy.onNetworkChange (wallet.js:51:1)
    at updateNetwork (AeSdkAepp.ts:106:1)
```

can this be ignored? other than that the update looks good to me 👍 

note: this is shown in the console before connecting the wallet. I am not sure if this is already a "problem" in the latest version of the boilerplate

**Comment by marc0olo** [comment]
> eventually pinata

do you really mean pinata or did you want to say pino? 🤔

**Comment by davidyuk** [comment]
> You are not connected to Wallet

It is not intended to be there, I'm looking for a fix

**Comment by thepiwo** [comment]
@marc0olo pinia sorry

**Comment by davidyuk** [comment]
I've fixed the error in a separate commit. The bug was because at the last moment before release I made sdk to call `onNetworkChange` right after connection, to avoid duplication of network initialization on aepp side https://github.com/aeternity/aepp-sdk-js/pull/1779.

Would be really good to update this repo to vite and pinia, but this would break the integration of contract builder in https://github.com/aeternity/aepp-boilerplate-vue/pull/24, so I won't do it 🙃

**Review by marc0olo — APPROVED** [review]

**Pull request merged**
