### PR TITLE
Upgrade to sdk v12

### LINKED ISSUE #6: network id doesn't update when switching network

### LINKED ISSUE #9: Upgrade to sdk v12
I think we will want to have the boilerplate up-to-date with the current SDK version

please upgrade dependencies and accommodate breaking changes when it will be released

https://github.com/aeternity/aepp-sdk-js/issues/1535

### LINKED ISSUE #10: boilerplate should configure 1 network
boilerplate only configures 1 network (either mainnet OR testnet) and provides respective error-handling when the user is connected to the wrong network with his wallet
so SDK uses either mainnet OR testnet based on config / env settings (doesn't matter what)

- [x] application should only configure 1 node (mainnet or testnet)
- [x] if wallet is configured for wrong network the aepp should "not work" (tell the user he is connected to the wrong network)
- [x] if wallet is configured for correct network the aepp should display some info about the connected account like it is right now (I guess)
- [x] decide about connection on command level
`run start` -> testnet
`run build` -> mainnet

it might be the case that the user connects to the app with his wallet connected to the wrong / not expected network
and the aepp needs to handle this accordingly and give respective feedback to the user in some modal, toast or whatever you think makes sense

### PR DESCRIPTION
**Pull request by janmichek**
fixes #9 
fixes https://github.com/aeternity/aepp-boilerplate-vue/issues/6
fixes #10 

https://user-images.githubusercontent.com/15363559/181011778-c501f238-5e9f-4aa7-9c67-f229fcdc4979.mp4

### CODE REVIEW

**Comment by marc0olo** [comment]
image

we should definitely address this

**Comment by marc0olo** [comment]
wallet connection generally works, but #6 is still a big problem in the current state. if we address #10 this should be irrelevant.

**Comment by janmichek** [comment]
> wallet connection generally works, but #6 is still a big problem in the current state. if we address #10 this should be irrelevant.

I will solve this in separate PR's, I am working on it atm. Or you want me to solve it in here?

**Comment by marc0olo** [comment]
> I will solve this in separate PR's, I am working on it atm. Or you want me to solve it in here?

in this specific case I would prefer checking all changes at once. for me it's fine to handle it in this PR 😅

**Comment by marc0olo** [comment]
my wallet was connected to `mainnet` and I actually received the alert that I am connected to the wrong network

image

still the frontend displays me information about the connection. I would prefer to not display it and instead show a text like `connected to wrong network. please switch to XXX in your wallet and reload the page`

what I really dislike is that frontend shows `ae_uat` in this case though my connected wallet is connected to `ae_mainnet`.

image

**Comment by janmichek** [comment]
> my wallet was connected to mainnet and I actually received the alert that I am connected to the wrong network

That is desired behavior. Maybe I can document it in readme.

When you run with command `yarn serve`-> it will run `serve-testnet` which stands for `vue-cli-service serve --mode development`. You are only allowed to connect to testnet.

The opposite behaviour you would achieve with yarn `serve-mainnet`

**Comment by janmichek** [comment]
> still the frontend displays me information about the connection. I would prefer to not display it and instead show a text like connected to wrong network. please switch to XXX in your wallet and reload the page

No probs, that was my suggestion as I had free hand in it. Will fix it by your suggestion.

**Comment by janmichek** [comment]
@marc0olo fixed like this. 
I like it better, however has one disatvantage now.
When the user erase the pre-made component WalletInfo to start development (which I think will probably happen), the message is not going to be displayed anywhere

https://user-images.githubusercontent.com/15363559/181066449-379f278a-d1f1-483e-a57f-f3f02031247b.mp4

**Comment by marc0olo** [comment]
> That is desired behavior. Maybe I can document it in readme.

yeah absolutely! I was more "complaining" about the paragraph that followed which is confusing after getting this **correct** alert :)

**Comment by marc0olo** [comment]
> When the user erase the pre-made component WalletInfo to start development (which I think will probably happen), the message is not going to be displayed anywhere

yeah but there is nothing more we can provide to get started correctly I guess. or do you have a proposal how to deal with it in a better way? at least we show the dev how to ensure the correct usage of wallet connection in that walletinfo component.

before your changes we didn't handle it accordingly which is bad practice IMO. so I am absolutely happy with the state we have now :)

will shortly double check the behavior on my laptop

**Review by marc0olo — APPROVED** [review]
looks good to me now. for other improvements and/or changes in the readme we can open new PRs. this is finally a state I am absolutely happy with :)

thanks @janmichek, feel free to merge!

**Pull request merged**
